import { cva, type VariantProps } from 'class-variance-authority';

export const statusVariants = cva('inline-flex w-fit items-center font-medium transition-colors duration-150', {
  variants: {
    variant: {
      dot: 'rounded border bg-background',
      solid: 'rounded text-white shadow-btn',
      soft: 'rounded',
      bar: 'gap-2 rounded-none border-l-4 pl-2',
    },
    color: {
      none: '',
      slate: '',
      gray: '',
      zinc: '',
      neutral: '',
      stone: '',
      red: '',
      orange: '',
      amber: '',
      yellow: '',
      lime: '',
      green: '',
      emerald: '',
      teal: '',
      cyan: '',
      sky: '',
      blue: '',
      indigo: '',
      violet: '',
      purple: '',
      fuchsia: '',
      pink: '',
      rose: '',
    },
    size: {
      sm: 'gap-1 px-1.5 py-0.5 text-[11px]',
      md: 'gap-1 px-2 py-0.5 text-xs',
      lg: 'gap-1.5 px-2.5 py-1 text-sm',
    },
  },
  defaultVariants: { variant: 'dot', color: 'gray', size: 'md' },
  compoundVariants: [
    // dot — outlined pill, colored dot + colored text
    { variant: 'dot', color: 'none', className: 'border-dashed border-gray-300 text-gray-400' },
    { variant: 'dot', color: 'slate', className: 'border-slate-300 text-slate-700' },
    { variant: 'dot', color: 'gray', className: 'border-gray-300 text-gray-700' },
    { variant: 'dot', color: 'zinc', className: 'border-zinc-300 text-zinc-700' },
    { variant: 'dot', color: 'neutral', className: 'border-neutral-300 text-neutral-700' },
    { variant: 'dot', color: 'stone', className: 'border-stone-300 text-stone-700' },
    { variant: 'dot', color: 'red', className: 'border-red-300 text-red-700' },
    { variant: 'dot', color: 'orange', className: 'border-orange-300 text-orange-700' },
    { variant: 'dot', color: 'amber', className: 'border-amber-300 text-amber-700' },
    { variant: 'dot', color: 'yellow', className: 'border-yellow-300 text-yellow-700' },
    { variant: 'dot', color: 'lime', className: 'border-lime-300 text-lime-700' },
    { variant: 'dot', color: 'green', className: 'border-green-300 text-green-700' },
    { variant: 'dot', color: 'emerald', className: 'border-emerald-300 text-emerald-700' },
    { variant: 'dot', color: 'teal', className: 'border-teal-300 text-teal-700' },
    { variant: 'dot', color: 'cyan', className: 'border-cyan-300 text-cyan-700' },
    { variant: 'dot', color: 'sky', className: 'border-sky-300 text-sky-700' },
    { variant: 'dot', color: 'blue', className: 'border-blue-300 text-blue-700' },
    { variant: 'dot', color: 'indigo', className: 'border-indigo-300 text-indigo-700' },
    { variant: 'dot', color: 'violet', className: 'border-violet-300 text-violet-700' },
    { variant: 'dot', color: 'purple', className: 'border-purple-300 text-purple-700' },
    { variant: 'dot', color: 'fuchsia', className: 'border-fuchsia-300 text-fuchsia-700' },
    { variant: 'dot', color: 'pink', className: 'border-pink-300 text-pink-700' },
    { variant: 'dot', color: 'rose', className: 'border-rose-300 text-rose-700' },
    // solid — filled pill, white text
    {
      variant: 'solid',
      color: 'none',
      className: 'border border-dashed border-gray-300 bg-transparent text-gray-400',
    },
    { variant: 'solid', color: 'slate', className: 'bg-slate-500' },
    { variant: 'solid', color: 'gray', className: 'bg-gray-500' },
    { variant: 'solid', color: 'zinc', className: 'bg-zinc-500' },
    { variant: 'solid', color: 'neutral', className: 'bg-neutral-500' },
    { variant: 'solid', color: 'stone', className: 'bg-stone-500' },
    { variant: 'solid', color: 'red', className: 'bg-red-500' },
    { variant: 'solid', color: 'orange', className: 'bg-orange-500' },
    { variant: 'solid', color: 'amber', className: 'bg-amber-500' },
    { variant: 'solid', color: 'yellow', className: 'bg-yellow-500' },
    { variant: 'solid', color: 'lime', className: 'bg-lime-500' },
    { variant: 'solid', color: 'green', className: 'bg-green-500' },
    { variant: 'solid', color: 'emerald', className: 'bg-emerald-500' },
    { variant: 'solid', color: 'teal', className: 'bg-teal-500' },
    { variant: 'solid', color: 'cyan', className: 'bg-cyan-500' },
    { variant: 'solid', color: 'sky', className: 'bg-sky-500' },
    { variant: 'solid', color: 'blue', className: 'bg-blue-500' },
    { variant: 'solid', color: 'indigo', className: 'bg-indigo-500' },
    { variant: 'solid', color: 'violet', className: 'bg-violet-500' },
    { variant: 'solid', color: 'purple', className: 'bg-purple-500' },
    { variant: 'solid', color: 'fuchsia', className: 'bg-fuchsia-500' },
    { variant: 'solid', color: 'pink', className: 'bg-pink-500' },
    { variant: 'solid', color: 'rose', className: 'bg-rose-500' },
    // soft — tinted background, bold colored text, no dot
    { variant: 'soft', color: 'none', className: 'bg-gray-50 text-gray-400' },
    { variant: 'soft', color: 'slate', className: 'bg-slate-100 text-slate-700' },
    { variant: 'soft', color: 'gray', className: 'bg-gray-100 text-gray-700' },
    { variant: 'soft', color: 'zinc', className: 'bg-zinc-100 text-zinc-700' },
    { variant: 'soft', color: 'neutral', className: 'bg-neutral-100 text-neutral-700' },
    { variant: 'soft', color: 'stone', className: 'bg-stone-100 text-stone-700' },
    { variant: 'soft', color: 'red', className: 'bg-red-100 text-red-700' },
    { variant: 'soft', color: 'orange', className: 'bg-orange-100 text-orange-700' },
    { variant: 'soft', color: 'amber', className: 'bg-amber-100 text-amber-700' },
    { variant: 'soft', color: 'yellow', className: 'bg-yellow-100 text-yellow-700' },
    { variant: 'soft', color: 'lime', className: 'bg-lime-100 text-lime-700' },
    { variant: 'soft', color: 'green', className: 'bg-green-100 text-green-700' },
    { variant: 'soft', color: 'emerald', className: 'bg-emerald-100 text-emerald-700' },
    { variant: 'soft', color: 'teal', className: 'bg-teal-100 text-teal-700' },
    { variant: 'soft', color: 'cyan', className: 'bg-cyan-100 text-cyan-700' },
    { variant: 'soft', color: 'sky', className: 'bg-sky-100 text-sky-700' },
    { variant: 'soft', color: 'blue', className: 'bg-blue-100 text-blue-700' },
    { variant: 'soft', color: 'indigo', className: 'bg-indigo-100 text-indigo-700' },
    { variant: 'soft', color: 'violet', className: 'bg-violet-100 text-violet-700' },
    { variant: 'soft', color: 'purple', className: 'bg-purple-100 text-purple-700' },
    { variant: 'soft', color: 'fuchsia', className: 'bg-fuchsia-100 text-fuchsia-700' },
    { variant: 'soft', color: 'pink', className: 'bg-pink-100 text-pink-700' },
    { variant: 'soft', color: 'rose', className: 'bg-rose-100 text-rose-700' },
    // bar — plain text with a colored left accent bar, for lists/timelines
    { variant: 'bar', color: 'none', className: 'border-gray-300 border-dashed text-gray-400' },
    { variant: 'bar', color: 'slate', className: 'border-slate-500 text-slate-700' },
    { variant: 'bar', color: 'gray', className: 'border-gray-500 text-gray-700' },
    { variant: 'bar', color: 'zinc', className: 'border-zinc-500 text-zinc-700' },
    { variant: 'bar', color: 'neutral', className: 'border-neutral-500 text-neutral-700' },
    { variant: 'bar', color: 'stone', className: 'border-stone-500 text-stone-700' },
    { variant: 'bar', color: 'red', className: 'border-red-500 text-red-700' },
    { variant: 'bar', color: 'orange', className: 'border-orange-500 text-orange-700' },
    { variant: 'bar', color: 'amber', className: 'border-amber-500 text-amber-700' },
    { variant: 'bar', color: 'yellow', className: 'border-yellow-500 text-yellow-700' },
    { variant: 'bar', color: 'lime', className: 'border-lime-500 text-lime-700' },
    { variant: 'bar', color: 'green', className: 'border-green-500 text-green-700' },
    { variant: 'bar', color: 'emerald', className: 'border-emerald-500 text-emerald-700' },
    { variant: 'bar', color: 'teal', className: 'border-teal-500 text-teal-700' },
    { variant: 'bar', color: 'cyan', className: 'border-cyan-500 text-cyan-700' },
    { variant: 'bar', color: 'sky', className: 'border-sky-500 text-sky-700' },
    { variant: 'bar', color: 'blue', className: 'border-blue-500 text-blue-700' },
    { variant: 'bar', color: 'indigo', className: 'border-indigo-500 text-indigo-700' },
    { variant: 'bar', color: 'violet', className: 'border-violet-500 text-violet-700' },
    { variant: 'bar', color: 'purple', className: 'border-purple-500 text-purple-700' },
    { variant: 'bar', color: 'fuchsia', className: 'border-fuchsia-500 text-fuchsia-700' },
    { variant: 'bar', color: 'pink', className: 'border-pink-500 text-pink-700' },
    { variant: 'bar', color: 'rose', className: 'border-rose-500 text-rose-700' },
  ],
});

export type StatusVariants = VariantProps<typeof statusVariants>;
