import { defineConfig } from 'tsdown'

export default defineConfig([
  {
    entry: [
      './packages/components/cards/simple-card.tsx',
      './packages/components/cards/product-card.tsx',
      './packages/components/cards/grid-product-card.tsx',

      './packages/components/data-display/country.tsx',
      './packages/components/data-display/data-list.tsx',
      './packages/components/data-display/date.tsx',
      './packages/components/data-display/date-tooltip.tsx',
      './packages/components/data-display/empty.tsx',
      './packages/components/data-display/name.tsx',
      './packages/components/data-display/phone-number.tsx',
      './packages/components/data-display/role-badge.tsx',
      './packages/components/data-display/statistic.tsx',
      './packages/components/data-display/user.tsx',

      './packages/components/dialogs/detail-dialog/index.tsx',
      './packages/components/dialogs/detail-dialog/component/sidebar.tsx',
      './packages/components/dialogs/confirm-dialog.tsx',
      './packages/components/dialogs/error-dialog.tsx',
      './packages/components/dialogs/form-dialog.tsx',
      './packages/components/dialogs/loading-dialog.tsx',

      './packages/components/features/search-modal/index.tsx',

      './packages/components/forms/form-wrapper.tsx',
      './packages/components/forms/combobox-field.tsx',
      './packages/components/forms/date-field.tsx',
      './packages/components/forms/multi-select-field.tsx',
      './packages/components/forms/number-field.tsx',
      './packages/components/forms/password-field.tsx',
      './packages/components/forms/select-field.tsx',
      './packages/components/forms/switch-field.tsx',
      './packages/components/forms/text-field.tsx',
      './packages/components/forms/textarea-field.tsx',

      './packages/components/layouts/main/index.tsx',
      './packages/components/layouts/app-layout/index.tsx',
      './packages/components/layouts/flex.tsx',
      './packages/components/layouts/grid.tsx',
      './packages/components/layouts/service-layout/index.ts',

      './packages/components/pages/FeatureDeveloping.tsx',
      './packages/components/pages/FeatureFixing.tsx',
      './packages/components/pages/NotAuthorized.tsx',
      './packages/components/pages/NotFound.tsx',

      './packages/components/products/add-cart-button.tsx',
      './packages/components/products/product-quantity-control.tsx',
      './packages/components/products/product-loading-page.tsx',

      './packages/components/systems/google.tsx',

      './packages/components/table/index.tsx',

      './packages/components/tanstack-form/index.tsx',

      './packages/components/typography/paragraph.tsx',
      './packages/components/typography/title.tsx',

      './packages/components/ui/buttons/add-new.tsx',
      './packages/components/ui/buttons/edit.tsx',
      './packages/components/ui/buttons/refresh.tsx',
      './packages/components/ui/buttons/trash.tsx',
      './packages/components/ui/buttons/upload-image.tsx',

      './packages/components/ui/inputs/search-input.tsx',

      './packages/components/ui/alert.tsx',
      './packages/components/ui/alert-dialog.tsx',
      './packages/components/ui/aspect-ratio.tsx',
      './packages/components/ui/avatar.tsx',
      './packages/components/ui/badge.tsx',
      './packages/components/ui/button.tsx',
      './packages/components/ui/button-group.tsx',
      './packages/components/ui/breadcrumb.tsx',
      './packages/components/ui/calendar.tsx',
      './packages/components/ui/card.tsx',
      './packages/components/ui/carousel.tsx',
      './packages/components/ui/collapsible.tsx',
      './packages/components/ui/command.tsx',
      './packages/components/ui/context-menu.tsx',
      './packages/components/ui/dialog.tsx',
      './packages/components/ui/drawer.tsx',
      './packages/components/ui/dropdown-menu.tsx',
      './packages/components/ui/empty.tsx',
      './packages/components/ui/field.tsx',
      './packages/components/ui/file-uploader.tsx',
      './packages/components/ui/form.tsx',
      './packages/components/ui/hover-card.tsx',
      './packages/components/ui/image.tsx',
      './packages/components/ui/input.tsx',
      './packages/components/ui/input-otp.tsx',
      './packages/components/ui/item.tsx',
      './packages/components/ui/label.tsx',
      './packages/components/ui/menubar.tsx',
      './packages/components/ui/multi-select.tsx',
      './packages/components/ui/navigation-menu.tsx',
      './packages/components/ui/pagination.tsx',
      './packages/components/ui/popover.tsx',
      './packages/components/ui/progress.tsx',
      './packages/components/ui/radio-group.tsx',
      './packages/components/ui/resizable.tsx',
      './packages/components/ui/scroll-area.tsx',
      './packages/components/ui/select.tsx',
      './packages/components/ui/separator.tsx',
      './packages/components/ui/sheet.tsx',
      './packages/components/ui/sidebar.tsx',
      './packages/components/ui/skeleton.tsx',
      './packages/components/ui/slider.tsx',
      './packages/components/ui/sonner.tsx',
      './packages/components/ui/spinner.tsx',
      './packages/components/ui/switch.tsx',
      './packages/components/ui/table.tsx',
      './packages/components/ui/tabs.tsx',
      './packages/components/ui/textarea.tsx',
      './packages/components/ui/toggle.tsx',
      './packages/components/ui/toggle-group.tsx',
      './packages/components/ui/tooltip.tsx',
    ],
    dts: true,
    exports: false,
    sourcemap: true,
    format: ['esm', 'cjs'],
    minify: true,
  },
])
